EventEmitter = require 'event-emitter'
module.exports = EventEmitterMixin = ->
  localEvents = new EventEmitter
  emit: -> @getEventEmitter().emit arguments...
  on:   -> @getEventEmitter().on arguments...
  once: -> @getEventEmitter().once arguments...
  off:  -> @getEventEmitter().off arguments...
  getEventEmitter: -> @props.events ? localEvents
