// Generated by CoffeeScript 1.8.0
(function() {
  var EventEmitter, ee2, globalEmitter, _ref;

  ee2 = require('eventemitter2');

  EventEmitter = (_ref = ee2 != null ? ee2.EventEmitter2 : void 0) != null ? _ref : ee2;

  globalEmitter = new EventEmitter({
    wildcard: true,
    delimitter: ':'
  });

  module.exports = {
    emit: function() {
      var _ref1;
      return (_ref1 = this.getContextEmitter()).emit.apply(_ref1, arguments);
    },
    on: function() {
      var _ref1;
      return (_ref1 = this.getContextEmitter()).on.apply(_ref1, arguments);
    },
    once: function() {
      var _ref1;
      return (_ref1 = this.getContextEmitter()).once.apply(_ref1, arguments);
    },
    off: function() {
      var _ref1;
      return (_ref1 = this.getContextEmitter()).off.apply(_ref1, arguments);
    },
    getContextEmitter: function() {
      var _ref1;
      return (_ref1 = this.props.emitter) != null ? _ref1 : globalEmitter;
    },
    getGlobalEmitter: function() {
      return globalEmitter;
    }
  };

}).call(this);
