// Generated by CoffeeScript 1.8.0
(function() {
  var EventEmitter, globalEmitter;

  EventEmitter = require('eventemitter2');

  globalEmitter = new EventEmitter({
    wildcard: true
  });

  module.exports = {
    emit: function() {
      var _ref;
      return (_ref = this.getContextEmitter()).emit.apply(_ref, arguments);
    },
    on: function() {
      var _ref;
      return (_ref = this.getContextEmitter()).on.apply(_ref, arguments);
    },
    once: function() {
      var _ref;
      return (_ref = this.getContextEmitter()).once.apply(_ref, arguments);
    },
    off: function() {
      var _ref;
      return (_ref = this.getContextEmitter()).off.apply(_ref, arguments);
    },
    getContextEmitter: function() {
      var _ref;
      return (_ref = this.props.emitter) != null ? _ref : globalEmitter;
    },
    getGlobalEmitter: function() {
      return globalEmitter;
    }
  };

}).call(this);
