// Generated by CoffeeScript 1.8.0
(function() {
  var EventEmitter, EventEmitterMixin;

  EventEmitter = require('event-emitter');

  module.exports = EventEmitterMixin = function() {
    var localEvents;
    localEvents = new EventEmitter;
    return {
      emit: function() {
        var _ref;
        return (_ref = this.getEventEmitter()).emit.apply(_ref, arguments);
      },
      on: function() {
        var _ref;
        return (_ref = this.getEventEmitter()).on.apply(_ref, arguments);
      },
      once: function() {
        var _ref;
        return (_ref = this.getEventEmitter()).once.apply(_ref, arguments);
      },
      off: function() {
        var _ref;
        return (_ref = this.getEventEmitter()).off.apply(_ref, arguments);
      },
      getEventEmitter: function() {
        var _ref;
        return (_ref = this.props.events) != null ? _ref : localEvents;
      }
    };
  };

}).call(this);
